<?php

/**
(c) Copyright 2008 Hewlett-Packard Development Company, L.P.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Generated by the Gagawa PHP TagBuilder Fri Dec 26 11:11:50 PST 2008

class Frame extends FertileNode {

	public function __construct(){
		parent::__construct("frame");
	}

	public function setFrameborder( $value ){ $this->setAttribute( "frameborder", $value ); return $this; }
	public function getFrameborder(){ return $this->getAttribute( "frameborder" ); }
	public function removeFrameborder(){ return $this->removeAttribute( "frameborder" ); }

	public function setLongdesc( $value ){ $this->setAttribute( "longdesc", $value ); return $this; }
	public function getLongdesc(){ return $this->getAttribute( "longdesc" ); }
	public function removeLongdesc(){ return $this->removeAttribute( "longdesc" ); }

	public function setMarginheight( $value ){ $this->setAttribute( "marginheight", $value ); return $this; }
	public function getMarginheight(){ return $this->getAttribute( "marginheight" ); }
	public function removeMarginheight(){ return $this->removeAttribute( "marginheight" ); }

	public function setMarginwidth( $value ){ $this->setAttribute( "marginwidth", $value ); return $this; }
	public function getMarginwidth(){ return $this->getAttribute( "marginwidth" ); }
	public function removeMarginwidth(){ return $this->removeAttribute( "marginwidth" ); }

	public function setName( $value ){ $this->setAttribute( "name", $value ); return $this; }
	public function getName(){ return $this->getAttribute( "name" ); }
	public function removeName(){ return $this->removeAttribute( "name" ); }

	public function setNoresize( $value ){ $this->setAttribute( "noresize", $value ); return $this; }
	public function getNoresize(){ return $this->getAttribute( "noresize" ); }
	public function removeNoresize(){ return $this->removeAttribute( "noresize" ); }

	public function setScrolling( $value ){ $this->setAttribute( "scrolling", $value ); return $this; }
	public function getScrolling(){ return $this->getAttribute( "scrolling" ); }
	public function removeScrolling(){ return $this->removeAttribute( "scrolling" ); }

	public function setSrc( $value ){ $this->setAttribute( "src", $value ); return $this; }
	public function getSrc(){ return $this->getAttribute( "src" ); }
	public function removeSrc(){ return $this->removeAttribute( "src" ); }

	public function setId( $value ){ $this->setAttribute( "id", $value ); return $this; }
	public function getId(){ return $this->getAttribute( "id" ); }
	public function removeId(){ return $this->removeAttribute( "id" ); }

	public function setCSSClass( $value ){ $this->setAttribute( "class", $value ); return $this; }
	public function getCSSClass(){ return $this->getAttribute( "class" ); }
	public function removeCSSClass(){ return $this->removeAttribute( "class" ); }

	public function setTitle( $value ){ $this->setAttribute( "title", $value ); return $this; }
	public function getTitle(){ return $this->getAttribute( "title" ); }
	public function removeTitle(){ return $this->removeAttribute( "title" ); }

	public function setStyle( $value ){ $this->setAttribute( "style", $value ); return $this; }
	public function getStyle(){ return $this->getAttribute( "style" ); }
	public function removeStyle(){ return $this->removeAttribute( "style" ); }

}

?>
