<?php

/**
(c) Copyright 2008 Hewlett-Packard Development Company, L.P.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Generated by the Gagawa PHP TagBuilder Fri Dec 26 11:11:50 PST 2008

class Img extends Node {

	public function __construct($alt, $src){
		parent::__construct("img");
		$this->setAlt( $alt );
		$this->setSrc( $src );
	}

	/* @Override */
	public function write(){
		return $this->writeOpen();
	}


	public function setAlt( $value ){ $this->setAttribute( "alt", $value ); return $this; }
	public function getAlt(){ return $this->getAttribute( "alt" ); }
	public function removeAlt(){ return $this->removeAttribute( "alt" ); }

	public function setSrc( $value ){ $this->setAttribute( "src", $value ); return $this; }
	public function getSrc(){ return $this->getAttribute( "src" ); }
	public function removeSrc(){ return $this->removeAttribute( "src" ); }

	public function setAlign( $value ){ $this->setAttribute( "align", $value ); return $this; }
	public function getAlign(){ return $this->getAttribute( "align" ); }
	public function removeAlign(){ return $this->removeAttribute( "align" ); }

	public function setBorder( $value ){ $this->setAttribute( "border", $value ); return $this; }
	public function getBorder(){ return $this->getAttribute( "border" ); }
	public function removeBorder(){ return $this->removeAttribute( "border" ); }

	public function setHeight( $value ){ $this->setAttribute( "height", $value ); return $this; }
	public function getHeight(){ return $this->getAttribute( "height" ); }
	public function removeHeight(){ return $this->removeAttribute( "height" ); }

	public function setHspace( $value ){ $this->setAttribute( "hspace", $value ); return $this; }
	public function getHspace(){ return $this->getAttribute( "hspace" ); }
	public function removeHspace(){ return $this->removeAttribute( "hspace" ); }

	public function setIsmap( $value ){ $this->setAttribute( "ismap", $value ); return $this; }
	public function getIsmap(){ return $this->getAttribute( "ismap" ); }
	public function removeIsmap(){ return $this->removeAttribute( "ismap" ); }

	public function setLongdesc( $value ){ $this->setAttribute( "longdesc", $value ); return $this; }
	public function getLongdesc(){ return $this->getAttribute( "longdesc" ); }
	public function removeLongdesc(){ return $this->removeAttribute( "longdesc" ); }

	public function setUsemap( $value ){ $this->setAttribute( "usemap", $value ); return $this; }
	public function getUsemap(){ return $this->getAttribute( "usemap" ); }
	public function removeUsemap(){ return $this->removeAttribute( "usemap" ); }

	public function setVspace( $value ){ $this->setAttribute( "vspace", $value ); return $this; }
	public function getVspace(){ return $this->getAttribute( "vspace" ); }
	public function removeVspace(){ return $this->removeAttribute( "vspace" ); }

	public function setWidth( $value ){ $this->setAttribute( "width", $value ); return $this; }
	public function getWidth(){ return $this->getAttribute( "width" ); }
	public function removeWidth(){ return $this->removeAttribute( "width" ); }

	public function setId( $value ){ $this->setAttribute( "id", $value ); return $this; }
	public function getId(){ return $this->getAttribute( "id" ); }
	public function removeId(){ return $this->removeAttribute( "id" ); }

	public function setCSSClass( $value ){ $this->setAttribute( "class", $value ); return $this; }
	public function getCSSClass(){ return $this->getAttribute( "class" ); }
	public function removeCSSClass(){ return $this->removeAttribute( "class" ); }

	public function setTitle( $value ){ $this->setAttribute( "title", $value ); return $this; }
	public function getTitle(){ return $this->getAttribute( "title" ); }
	public function removeTitle(){ return $this->removeAttribute( "title" ); }

	public function setStyle( $value ){ $this->setAttribute( "style", $value ); return $this; }
	public function getStyle(){ return $this->getAttribute( "style" ); }
	public function removeStyle(){ return $this->removeAttribute( "style" ); }

	public function setLang( $value ){ $this->setAttribute( "lang", $value ); return $this; }
	public function getLang(){ return $this->getAttribute( "lang" ); }
	public function removeLang(){ return $this->removeAttribute( "lang" ); }

	public function setXMLLang( $value ){ $this->setAttribute( "xml:lang", $value ); return $this; }
	public function getXMLLang(){ return $this->getAttribute( "xml:lang" ); }
	public function removeXMLLang(){ return $this->removeAttribute( "xml:lang" ); }

}

?>
