<?php

/**
(c) Copyright 2008 Hewlett-Packard Development Company, L.P.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Generated by the Gagawa PHP TagBuilder Fri Dec 26 11:11:50 PST 2008

class Script extends FertileNode {

	public function __construct($type){
		parent::__construct("script");
		$this->setType( $type );
	}

	public function setType( $value ){ $this->setAttribute( "type", $value ); return $this; }
	public function getType(){ return $this->getAttribute( "type" ); }
	public function removeType(){ return $this->removeAttribute( "type" ); }

	public function setCharset( $value ){ $this->setAttribute( "charset", $value ); return $this; }
	public function getCharset(){ return $this->getAttribute( "charset" ); }
	public function removeCharset(){ return $this->removeAttribute( "charset" ); }

	public function setDefer( $value ){ $this->setAttribute( "defer", $value ); return $this; }
	public function getDefer(){ return $this->getAttribute( "defer" ); }
	public function removeDefer(){ return $this->removeAttribute( "defer" ); }

	public function setLanguage( $value ){ $this->setAttribute( "language", $value ); return $this; }
	public function getLanguage(){ return $this->getAttribute( "language" ); }
	public function removeLanguage(){ return $this->removeAttribute( "language" ); }

	public function setSrc( $value ){ $this->setAttribute( "src", $value ); return $this; }
	public function getSrc(){ return $this->getAttribute( "src" ); }
	public function removeSrc(){ return $this->removeAttribute( "src" ); }

	public function setXmlspace( $value ){ $this->setAttribute( "xmlspace", $value ); return $this; }
	public function getXmlspace(){ return $this->getAttribute( "xmlspace" ); }
	public function removeXmlspace(){ return $this->removeAttribute( "xmlspace" ); }

}

?>
