<?php

/**
(c) Copyright 2008 Hewlett-Packard Development Company, L.P.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

// Generated by the Gagawa PHP TagBuilder Fri Dec 26 11:11:50 PST 2008

class Table extends FertileNode {

	public function __construct(){
		parent::__construct("table");
	}

	public function setAlign( $value ){ $this->setAttribute( "align", $value ); return $this; }
	public function getAlign(){ return $this->getAttribute( "align" ); }
	public function removeAlign(){ return $this->removeAttribute( "align" ); }

	public function setBgcolor( $value ){ $this->setAttribute( "bgcolor", $value ); return $this; }
	public function getBgcolor(){ return $this->getAttribute( "bgcolor" ); }
	public function removeBgcolor(){ return $this->removeAttribute( "bgcolor" ); }

	public function setBorder( $value ){ $this->setAttribute( "border", $value ); return $this; }
	public function getBorder(){ return $this->getAttribute( "border" ); }
	public function removeBorder(){ return $this->removeAttribute( "border" ); }

	public function setCellpadding( $value ){ $this->setAttribute( "cellpadding", $value ); return $this; }
	public function getCellpadding(){ return $this->getAttribute( "cellpadding" ); }
	public function removeCellpadding(){ return $this->removeAttribute( "cellpadding" ); }

	public function setCellspacing( $value ){ $this->setAttribute( "cellspacing", $value ); return $this; }
	public function getCellspacing(){ return $this->getAttribute( "cellspacing" ); }
	public function removeCellspacing(){ return $this->removeAttribute( "cellspacing" ); }

	public function setFrame( $value ){ $this->setAttribute( "frame", $value ); return $this; }
	public function getFrame(){ return $this->getAttribute( "frame" ); }
	public function removeFrame(){ return $this->removeAttribute( "frame" ); }

	public function setRules( $value ){ $this->setAttribute( "rules", $value ); return $this; }
	public function getRules(){ return $this->getAttribute( "rules" ); }
	public function removeRules(){ return $this->removeAttribute( "rules" ); }

	public function setSummary( $value ){ $this->setAttribute( "summary", $value ); return $this; }
	public function getSummary(){ return $this->getAttribute( "summary" ); }
	public function removeSummary(){ return $this->removeAttribute( "summary" ); }

	public function setWidth( $value ){ $this->setAttribute( "width", $value ); return $this; }
	public function getWidth(){ return $this->getAttribute( "width" ); }
	public function removeWidth(){ return $this->removeAttribute( "width" ); }

	public function setId( $value ){ $this->setAttribute( "id", $value ); return $this; }
	public function getId(){ return $this->getAttribute( "id" ); }
	public function removeId(){ return $this->removeAttribute( "id" ); }

	public function setCSSClass( $value ){ $this->setAttribute( "class", $value ); return $this; }
	public function getCSSClass(){ return $this->getAttribute( "class" ); }
	public function removeCSSClass(){ return $this->removeAttribute( "class" ); }

	public function setTitle( $value ){ $this->setAttribute( "title", $value ); return $this; }
	public function getTitle(){ return $this->getAttribute( "title" ); }
	public function removeTitle(){ return $this->removeAttribute( "title" ); }

	public function setStyle( $value ){ $this->setAttribute( "style", $value ); return $this; }
	public function getStyle(){ return $this->getAttribute( "style" ); }
	public function removeStyle(){ return $this->removeAttribute( "style" ); }

	public function setDir( $value ){ $this->setAttribute( "dir", $value ); return $this; }
	public function getDir(){ return $this->getAttribute( "dir" ); }
	public function removeDir(){ return $this->removeAttribute( "dir" ); }

	public function setLang( $value ){ $this->setAttribute( "lang", $value ); return $this; }
	public function getLang(){ return $this->getAttribute( "lang" ); }
	public function removeLang(){ return $this->removeAttribute( "lang" ); }

	public function setXMLLang( $value ){ $this->setAttribute( "xml:lang", $value ); return $this; }
	public function getXMLLang(){ return $this->getAttribute( "xml:lang" ); }
	public function removeXMLLang(){ return $this->removeAttribute( "xml:lang" ); }

}

?>
